version: "3.9"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - WHATSAPP_CLOUD_GRAPHAPI_PHONE_NUMBER_ID=${WHATSAPP_CLOUD_GRAPHAPI_PHONE_NUMBER_ID}
      - WHATSAPP_CLOUD_GRAPHAPI_ACCESS_TOKEN=${WHATSAPP_CLOUD_GRAPHAPI_ACCESS_TOKEN}
      - WHATSAPP_CLOUD_WEBHOOKS_VERIFY_TOKEN=${WHATSAPP_CLOUD_WEBHOOKS_VERIFY_TOKEN}
      - WHATSAPP_CLOUD_WEBHOOKS_SECRET=${WHATSAPP_CLOUD_WEBHOOKS_SECRET}
