version: "3.9"
networks:
  bridge:
    external: true
  traefik_net:
    external: true

services:
  app:
    image: chatally/demo-app
    networks:
      - traefik_net
      - bridge
    volumes:
      - ${PWD}/data:/usr/src/app/data
      # Time sync with host
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    deploy:
      labels:
        - traefik.enable=true
        - traefik.http.routers.${STACK}.middlewares=sec-headers@file
        - traefik.http.routers.${STACK}.rule=Host(`${SITE}`)
        - traefik.http.routers.${STACK}.tls.certresolver=letsencrypt
        - traefik.http.routers.${STACK}.tls=true
        - traefik.http.services.${STACK}.loadbalancer.server.port=3000
