name: Deploy to remote server via scp/ssh

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to remote
    runs-on: ubuntu-latest
    # needs: tests // we might want to run some tests before deploying?
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure SSH in runner
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          mkdir -p ~/.ssh/
          printf "%s" "${{ secrets.SSH_USER }}" > ~/.ssh/remote.key
          chmod 600 ~/.ssh/remote.key
          cat >~/.ssh/config <<END
          Host REMOTE_SERVER
            HostName ${{ secrets.SSH_HOST }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/remote.key
            StrictHostKeyChecking no
          END

      - name: Write variables to env file
        run: |
          cat >app/.env <<END
          WHATSAPP_CLOUD_GRAPHAPI_PHONE_NUMBER_ID=${{ secrets.WA_PHONE_NUMBER_ID }}
          WHATSAPP_CLOUD_GRAPHAPI_ACCESS_TOKEN=${{ secrets.WA_ACCESS_TOKEN }}
          WHATSAPP_CLOUD_WEBHOOKS_VERIFY_TOKEN=${{ secrets.WA_VERIFY_TOKEN }}
          WHATSAPP_CLOUD_WEBHOOKS_SECRET=${{ secrets.WA_SECRET }}
          END

      - name: Copy sources
        run: |
          scp -r docker-compose.yml Dockerfile restart-server.sh app REMOTE_SERVER:~/src

      - name: Restart server (remotely)
        run: |
          ssh REMOTE_SERVER '~/src/restart-server.sh'
